import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";
import SessionProvider from "@/client/components/SessionProvider";
import NavbarComponent from "@/client/components/Navbar";
import FooterComponent from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sound Store Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="bg">
      <head>
        {/* Place your head elements here */}
      </head>
      <body>
        <SessionProvider session={session}>
          <header><NavbarComponent /></header>
          {children}
          <footer><FooterComponent /></footer>
        </SessionProvider>
      </body>
    </html>
  );
}
