import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";

import SessionProvider from "@/client/components/SessionProvider";
import NavbarComponent from "@/client/components/Navbar";
import FooterComponent from "@/app/components/Footer";
import { ThemesProvider } from "@/app/provider";
import { AvatarProvider } from "@/libs/contexts/AvatarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sound Store Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="bg" suppressHydrationWarning>
      <head>{/* Place your head elements here */}</head>
      <body>
        <SessionProvider session={session}>
          <ThemesProvider>
            <AvatarProvider>
              <header>
                <NavbarComponent /> 
              </header>
            </AvatarProvider>
          </ThemesProvider>
          {children}
          <footer>
            <FooterComponent />
          </footer>
        </SessionProvider>
      </body>
    </html>
  );
}
